"""Add enterprise metadata and network links

Revision ID: 07f2e4428d8c
Revises: 95e8ed0dc6e7
Create Date: 2026-07-19 16:19:59.098472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f2e4428d8c'
down_revision: Union[str, Sequence[str], None] = '95e8ed0dc6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_links',
    sa.Column('source_zone_id', sa.String(length=36), nullable=False),
    sa.Column('target_zone_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('trust_level', sa.String(length=50), nullable=True),
    sa.Column('routing_direction', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_zone_id'], ['network_zones.id'], ),
    sa.ForeignKeyConstraint(['target_zone_id'], ['network_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('company_profiles', sa.Column('business_domain', sa.String(length=100), nullable=True))
    op.add_column('company_profiles', sa.Column('security_level', sa.String(length=100), nullable=True))
    op.add_column('company_profiles', sa.Column('factory_count', sa.Integer(), nullable=True))
    op.add_column('company_profiles', sa.Column('office_count', sa.Integer(), nullable=True))
    op.add_column('company_profiles', sa.Column('critical_infrastructure_type', sa.String(length=100), nullable=True))
    op.add_column('company_profiles', sa.Column('timezone', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('criticality_level', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('operating_system', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('last_patch_date', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('maintenance_window', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('communication_protocol', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('vendor', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('asset_group', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('role_level', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('hire_date', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('last_login', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('badge_id', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('clearance_level', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('employment_type', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('workstation', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('assigned_projects', sa.JSON(), nullable=True))
    op.add_column('employees', sa.Column('security_training_completed', sa.Boolean(), nullable=True))
    op.add_column('network_zones', sa.Column('trust_level', sa.String(length=50), nullable=True))
    op.add_column('network_zones', sa.Column('routing_direction', sa.String(length=50), nullable=True))
    op.add_column('scenarios', sa.Column('scenario_type', sa.String(length=100), nullable=True))
    op.add_column('scenarios', sa.Column('target_department_id', sa.String(length=36), nullable=True))
    op.add_column('scenarios', sa.Column('estimated_duration', sa.String(length=100), nullable=True))
    op.add_column('scenarios', sa.Column('required_roles', sa.JSON(), nullable=True))
    op.add_column('scenarios', sa.Column('tags', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'scenarios', 'departments', ['target_department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scenarios', type_='foreignkey')
    op.drop_column('scenarios', 'tags')
    op.drop_column('scenarios', 'required_roles')
    op.drop_column('scenarios', 'estimated_duration')
    op.drop_column('scenarios', 'target_department_id')
    op.drop_column('scenarios', 'scenario_type')
    op.drop_column('network_zones', 'routing_direction')
    op.drop_column('network_zones', 'trust_level')
    op.drop_column('employees', 'security_training_completed')
    op.drop_column('employees', 'assigned_projects')
    op.drop_column('employees', 'workstation')
    op.drop_column('employees', 'employment_type')
    op.drop_column('employees', 'clearance_level')
    op.drop_column('employees', 'badge_id')
    op.drop_column('employees', 'last_login')
    op.drop_column('employees', 'hire_date')
    op.drop_column('employees', 'role_level')
    op.drop_column('devices', 'asset_group')
    op.drop_column('devices', 'vendor')
    op.drop_column('devices', 'communication_protocol')
    op.drop_column('devices', 'maintenance_window')
    op.drop_column('devices', 'last_patch_date')
    op.drop_column('devices', 'operating_system')
    op.drop_column('devices', 'criticality_level')
    op.drop_column('company_profiles', 'timezone')
    op.drop_column('company_profiles', 'critical_infrastructure_type')
    op.drop_column('company_profiles', 'office_count')
    op.drop_column('company_profiles', 'factory_count')
    op.drop_column('company_profiles', 'security_level')
    op.drop_column('company_profiles', 'business_domain')
    op.drop_table('network_links')
    # ### end Alembic commands ###
