"""Add capabilities to User, graph to ScenarioState, and scenario_state_id to Report

Revision ID: 6ab88f3a034d
Revises: 36b3e561d9c4
Create Date: 2026-07-21 13:11:39.745993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab88f3a034d'
down_revision: Union[str, Sequence[str], None] = '36b3e561d9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('scenario_state_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'reports', 'scenario_states', ['scenario_state_id'], ['id'])
    op.add_column('scenario_states', sa.Column('completed_stages', sa.JSON(), nullable=True))
    op.add_column('scenario_states', sa.Column('flags_captured', sa.JSON(), nullable=True))
    op.add_column('scenario_states', sa.Column('total_stages', sa.Integer(), nullable=False))
    op.add_column('scenario_states', sa.Column('vulnerability_graph', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('capabilities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'capabilities')
    op.drop_column('scenario_states', 'vulnerability_graph')
    op.drop_column('scenario_states', 'total_stages')
    op.drop_column('scenario_states', 'flags_captured')
    op.drop_column('scenario_states', 'completed_stages')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'scenario_state_id')
    # ### end Alembic commands ###
