"""Add hints_used

Revision ID: 86c77288ca4b
Revises: 6ab88f3a034d
Create Date: 2026-07-23 23:07:56.042301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c77288ca4b'
down_revision: Union[str, Sequence[str], None] = '6ab88f3a034d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_states', sa.Column('hints_used', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario_states', 'hints_used')
    # ### end Alembic commands ###
