"""add workflow enums

Revision ID: 921409651aaa
Revises: 98b947f37ebf
Create Date: 2026-07-19 14:12:28.666571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921409651aaa'
down_revision: Union[str, Sequence[str], None] = '98b947f37ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE devicestatusenum ADD VALUE 'NEW' BEFORE 'ONLINE'")
    op.execute("ALTER TYPE devicestatusenum ADD VALUE 'REGISTERED' BEFORE 'ONLINE'")
    op.execute("ALTER TYPE devicestatusenum ADD VALUE 'CONFIGURED' BEFORE 'ONLINE'")
    op.execute("ALTER TYPE devicestatusenum ADD VALUE 'DECOMMISSIONED' AFTER 'OFFLINE'")

    op.execute("ALTER TYPE ticketstatusenum ADD VALUE 'ASSIGNED' AFTER 'OPEN'")
    op.execute("ALTER TYPE ticketstatusenum ADD VALUE 'UNDER_REVIEW' AFTER 'IN_PROGRESS'")
    op.execute("ALTER TYPE ticketstatusenum ADD VALUE 'CLOSED' AFTER 'RESOLVED'")
    op.execute("ALTER TYPE ticketstatusenum ADD VALUE 'REJECTED' AFTER 'CLOSED'")


    employeestatusenum = sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'TERMINATED', name='employeestatusenum')
    employeestatusenum.create(op.get_bind(), checkfirst=True)
    firmwarestatusenum = sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'DEPLOYED', 'RETIRED', name='firmwarestatusenum')
    firmwarestatusenum.create(op.get_bind(), checkfirst=True)
    inventorystatusenum = sa.Enum('CREATED', 'AVAILABLE', 'ALLOCATED', 'CONSUMED', 'RESTOCKED', name='inventorystatusenum')
    inventorystatusenum.create(op.get_bind(), checkfirst=True)
    reportstatusenum = sa.Enum('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED', name='reportstatusenum')
    reportstatusenum.create(op.get_bind(), checkfirst=True)
    op.add_column('employees', sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'TERMINATED', name='employeestatusenum'), nullable=False, server_default='PENDING'))
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.add_column('firmwares', sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'DEPLOYED', 'RETIRED', name='firmwarestatusenum'), nullable=False, server_default='DRAFT'))
    op.add_column('inventory', sa.Column('status', sa.Enum('CREATED', 'AVAILABLE', 'ALLOCATED', 'CONSUMED', 'RESTOCKED', name='inventorystatusenum'), nullable=False, server_default='CREATED'))
    op.add_column('reports', sa.Column('status', sa.Enum('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED', name='reportstatusenum'), nullable=False, server_default='DRAFT'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE devicestatusenum ADD VALUE 'NEW' BEFORE 'ONLINE'")
    op.execute("ALTER TYPE devicestatusenum ADD VALUE 'REGISTERED' BEFORE 'ONLINE'")
    op.execute("ALTER TYPE devicestatusenum ADD VALUE 'CONFIGURED' BEFORE 'ONLINE'")
    op.execute("ALTER TYPE devicestatusenum ADD VALUE 'DECOMMISSIONED' AFTER 'OFFLINE'")

    op.execute("ALTER TYPE ticketstatusenum ADD VALUE 'ASSIGNED' AFTER 'OPEN'")
    op.execute("ALTER TYPE ticketstatusenum ADD VALUE 'UNDER_REVIEW' AFTER 'IN_PROGRESS'")
    op.execute("ALTER TYPE ticketstatusenum ADD VALUE 'CLOSED' AFTER 'RESOLVED'")
    op.execute("ALTER TYPE ticketstatusenum ADD VALUE 'REJECTED' AFTER 'CLOSED'")

    op.drop_column('reports', 'status')
    op.drop_column('inventory', 'status')
    op.drop_column('firmwares', 'status')
    op.alter_column('employees', 'last_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('employees', 'status')
    # ### end Alembic commands ###
