"""Milestone_3D

Revision ID: 95e8ed0dc6e7
Revises: c24829d7ca3d
Create Date: 2026-07-19 15:56:36.388608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e8ed0dc6e7'
down_revision: Union[str, Sequence[str], None] = 'c24829d7ca3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profiles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('headquarters', sa.String(length=255), nullable=True),
    sa.Column('business_units', sa.JSON(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('network_zones',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('subnet', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('business_context', sa.String(length=2000), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('expected_learning_objectives', sa.JSON(), nullable=True),
    sa.Column('affected_assets', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('devices', sa.Column('serial_number', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('manufacturer', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('warranty_expiry', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('lifecycle_status', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('assigned_engineer_id', sa.String(length=36), nullable=True))
    op.add_column('devices', sa.Column('network_zone_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'devices', 'employees', ['assigned_engineer_id'], ['id'])
    op.create_foreign_key(None, 'devices', 'network_zones', ['network_zone_id'], ['id'])
    op.add_column('employees', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('shift', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('office', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('skills', sa.JSON(), nullable=True))
    op.add_column('employees', sa.Column('manager_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'employees', 'employees', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'manager_id')
    op.drop_column('employees', 'skills')
    op.drop_column('employees', 'office')
    op.drop_column('employees', 'shift')
    op.drop_column('employees', 'title')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'network_zone_id')
    op.drop_column('devices', 'assigned_engineer_id')
    op.drop_column('devices', 'lifecycle_status')
    op.drop_column('devices', 'warranty_expiry')
    op.drop_column('devices', 'manufacturer')
    op.drop_column('devices', 'serial_number')
    op.drop_table('scenarios')
    op.drop_table('network_zones')
    op.drop_table('company_profiles')
    # ### end Alembic commands ###
