"""Add business_impact to scenario

Revision ID: affd0c92b51c
Revises: 07f2e4428d8c
Create Date: 2026-07-19 16:39:25.432378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'affd0c92b51c'
down_revision: Union[str, Sequence[str], None] = '07f2e4428d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('business_impact', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'business_impact')
    # ### end Alembic commands ###
