"""Milestone 3B tables

Revision ID: c24829d7ca3d
Revises: 921409651aaa
Create Date: 2026-07-19 14:49:03.648910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24829d7ca3d'
down_revision: Union[str, Sequence[str], None] = '921409651aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('target_entity', sa.String(length=100), nullable=False),
    sa.Column('target_entity_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('previous_state', sa.String(length=100), nullable=True),
    sa.Column('new_state', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_entity'), 'audit_logs', ['target_entity'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_entity_id'), 'audit_logs', ['target_entity_id'], unique=False)
    op.create_table('workflow_history',
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('old_state', sa.String(length=100), nullable=True),
    sa.Column('new_state', sa.String(length=100), nullable=False),
    sa.Column('transition_time', sa.DateTime(), nullable=False),
    sa.Column('triggered_by', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('transition_duration', sa.Integer(), nullable=True),
    sa.Column('transition_method', sa.String(length=100), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_history_entity'), 'workflow_history', ['entity'], unique=False)
    op.create_index(op.f('ix_workflow_history_entity_id'), 'workflow_history', ['entity_id'], unique=False)
    sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR', 'CRITICAL', name='notificationseverityenum').create(op.get_bind())
    op.add_column('notifications', sa.Column('severity', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR', 'CRITICAL', name='notificationseverityenum'), nullable=False))
    op.add_column('notifications', sa.Column('recipient_id', sa.String(length=36), nullable=True))
    op.add_column('notifications', sa.Column('read_status', sa.Boolean(), nullable=False))
    op.add_column('notifications', sa.Column('category', sa.String(length=100), nullable=True))
    op.alter_column('notifications', 'message',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['recipient_id'], ['id'])
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'priority')
    op.drop_column('notifications', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('priority', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.alter_column('notifications', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.drop_column('notifications', 'category')
    op.drop_column('notifications', 'read_status')
    op.drop_column('notifications', 'recipient_id')
    op.drop_column('notifications', 'severity')
    op.drop_index(op.f('ix_workflow_history_entity_id'), table_name='workflow_history')
    op.drop_index(op.f('ix_workflow_history_entity'), table_name='workflow_history')
    op.drop_table('workflow_history')
    op.drop_index(op.f('ix_audit_logs_target_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_entity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
