with open('backend/alembic/versions/921409651aaa_add_workflow_enums.py', 'r') as f:
    content = f.read()

upgrade_additions = '''
    op.execute("ALTER TYPE devicestatusenum ADD VALUE 'NEW' BEFORE 'ONLINE'")
    op.execute("ALTER TYPE devicestatusenum ADD VALUE 'REGISTERED' BEFORE 'ONLINE'")
    op.execute("ALTER TYPE devicestatusenum ADD VALUE 'CONFIGURED' BEFORE 'ONLINE'")
    op.execute("ALTER TYPE devicestatusenum ADD VALUE 'DECOMMISSIONED' AFTER 'OFFLINE'")

    op.execute("ALTER TYPE ticketstatusenum ADD VALUE 'ASSIGNED' AFTER 'OPEN'")
    op.execute("ALTER TYPE ticketstatusenum ADD VALUE 'UNDER_REVIEW' AFTER 'IN_PROGRESS'")
    op.execute("ALTER TYPE ticketstatusenum ADD VALUE 'CLOSED' AFTER 'RESOLVED'")
    op.execute("ALTER TYPE ticketstatusenum ADD VALUE 'REJECTED' AFTER 'CLOSED'")
'''

content = content.replace("    # ### commands auto generated by Alembic - please adjust! ###", "    # ### commands auto generated by Alembic - please adjust! ###" + upgrade_additions)

# Alembic Enum add_column in Postgres needs the type created first sometimes, but Alembic might do it for us. Let's create it explicitly just in case to avoid errors.
upgrade_types = '''
    employeestatusenum = sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'TERMINATED', name='employeestatusenum')
    employeestatusenum.create(op.get_bind(), checkfirst=True)
    firmwarestatusenum = sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'DEPLOYED', 'RETIRED', name='firmwarestatusenum')
    firmwarestatusenum.create(op.get_bind(), checkfirst=True)
    inventorystatusenum = sa.Enum('CREATED', 'AVAILABLE', 'ALLOCATED', 'CONSUMED', 'RESTOCKED', name='inventorystatusenum')
    inventorystatusenum.create(op.get_bind(), checkfirst=True)
    reportstatusenum = sa.Enum('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED', name='reportstatusenum')
    reportstatusenum.create(op.get_bind(), checkfirst=True)
'''
content = content.replace("    op.add_column('employees', sa.Column('status'", upgrade_types + "    op.add_column('employees', sa.Column('status'")

with open('backend/alembic/versions/921409651aaa_add_workflow_enums.py', 'w') as f:
    f.write(content)
