from fastapi import APIRouter, Depends
from pydantic import BaseModel
from sqlalchemy.orm import Session
from typing import Any
from app.api import deps
from app.models.user import User

class SearchRequest(BaseModel):
    query: str

router = APIRouter()

# Marker value present in out-of-scope results for OPF Stage 3
OPF_LEAKED_RESULTS = [
    {
        "id": "log_sys_001",
        "title": "System Audit Log - Firmware Push Event",
        "category": "Deployment Logs",
        "snippet": "CRITICAL: Unauthorized firmware update pushed to Production Line 2. Session privilege override recorded.",
        "source": "syslog_sec_archive"
    },
    {
        "id": "log_sys_002",
        "title": "Production Line 2 Exception Log",
        "category": "System Logs",
        "snippet": "Line 2 halt triggered due to firmware checksum mismatch. Initiated by engineer account.",
        "source": "ot_mon_daemon"
    }
]

# SE Stage 2: out-of-scope results containing a backup filename reference
SE_LEAKED_RESULTS = [
    {
        "id": "dev_backup_ref_001",
        "title": "Device Config Backup Reference — HMI Terminal",
        "category": "Device Records",
        "snippet": "Last automated backup on record for HMI Terminal Unit-7734.",
        "backup_file": "ot-ctrl-backup-line7.cfg",
        "device_id": "hmi-7734",
        "source": "device_asset_registry"
    },
    {
        "id": "dev_backup_ref_002",
        "title": "Internal Asset Export Fragment",
        "category": "Configuration Archive",
        "snippet": "config_backup_path: /app/backups/ot-ctrl-backup-line7.cfg — generated by scheduled maintenance job.",
        "source": "config_audit_log"
    }
]


@router.post("/", response_model=dict)
def perform_global_search(
    req: SearchRequest,
    db: Session = Depends(deps.get_db),
    current_user: User = Depends(deps.get_current_active_user)
) -> Any:
    """
    Global search endpoint.
    For OPF Stage 3: injection patterns cause deployment log leakage.
    For SE Stage 2: injection patterns cause device backup config reference leakage.
    Stage advancement is outcome-based — what data actually came back — not what string was typed.
    """
    from app.scenarios.stage_gate import get_in_progress_state, advance_if_stage_matches

    query_lower = req.query.lower()

    # Determine which scenario the user is on, to serve the right leaked data
    active_state = get_in_progress_state(db)
    active_scenario = active_state.scenario_id if active_state else None

    if active_scenario == "operation_phantom_firmware":
        # Strict payload requirement for OPF as requested by user
        if req.query == '" OR 1=1 --':
            results = OPF_LEAKED_RESULTS
            # Outcome: deployment log data was actually served
            advance_if_stage_matches(db, "POST /api/v1/search",
                                     {"leaked_data": True})
        else:
            # Any other query shows absolutely no results for OPF
            results = []
    else:
        # Detect injection patterns (broad — any technique that causes out-of-scope data to appear)
        injection_indicators = ["'", '"', "or ", "and ", "1=1", "1 =1", "%", "select", "union",
                                "drop", "--", "/*", "*/", "xp_", "exec", "cast(", "convert(",
                                "information_schema", "deploy", "firmware", "backup", "log"]
        is_injection = any(term in query_lower for term in injection_indicators)

        if is_injection:
            if active_scenario == "silent_exfiltration":
                results = SE_LEAKED_RESULTS
                # Outcome: backup filename reference was actually served
                advance_if_stage_matches(db, "POST /api/v1/search",
                                         {"injection_leak": True})
            else:
                results = OPF_LEAKED_RESULTS
                advance_if_stage_matches(db, "POST /api/v1/search",
                                         {"leaked_data": True})
        else:
            results = [
                {
                    "id": "res_001",
                    "title": f"General Search Result for '{req.query}'",
                    "category": "Documentation",
                    "snippet": "No specific system anomalies found matching query.",
                    "source": "kb_articles"
                }
            ]

    return {"query": req.query, "count": len(results), "items": results}
